## 本地图片上传路径
name: newbee-mall-api-go
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: bahutech/newbee-mall-api-go
  name: newbee-mall-api-go
local:
  path: static
mysql:
  path: db-mysql-nyc3-32832-do-user-18233818-0.f.db.ondigitalocean.com
  port: "25060"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: newbee_mall_db_v2
  username: doadmin
  password: AVNS_L7-zmNJAGCl5CWBNSRR
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[newbee_mall]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
